from pathlib import Path

path = Path('components/WorkflowWorkspaceV2.tsx')
text = path.read_text()

old_import = 'import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, MapPin, ShieldCheck } from "lucide-react";'
new_import = 'import { BriefcaseBusiness, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, MapPin, ShieldCheck } from "lucide-react";'
if old_import not in text:
    raise SystemExit('Expected lucide import not found')
text = text.replace(old_import, new_import, 1)

old_top = '''    <div className="flex flex-col gap-2">\n      <h1 className="page-title">{profile.first_name ? `${profile.first_name}, find your next shift` : "Find your next shift"}</h1>\n      <p className="page-subtitle">Tap a date to see matching offices, invitations, applications and booked shifts.</p>\n      <button type="button" onClick={() => setAvailabilityOpen(true)} className="mt-2 inline-flex w-fit items-center justify-center gap-2 rounded-xl bg-[#04A62F] px-4 py-2.5 text-sm font-black text-white shadow-sm transition hover:bg-[#038c28] focus:outline-none focus:ring-2 focus:ring-[#04A62F]/30"><CalendarDays size={18} />Post Availability</button>\n    </div>'''
new_top = '''    <div className="flex flex-col gap-2">\n      <h1 className="page-title">{profile.first_name ? `${profile.first_name}, find your next shift` : "Find your next shift"}</h1>\n      <p className="page-subtitle">Tap a date to see matching offices, invitations, applications and booked shifts.</p>\n    </div>'''
if old_top not in text:
    raise SystemExit('Top Post Availability block not found')
text = text.replace(old_top, new_top, 1)

old_header = '''        <div className="flex flex-wrap items-start justify-between gap-3">\n          <div>\n            <div className="mb-3 flex flex-wrap items-center gap-2">\n              <button type="button" disabled={!canGoBack} onClick={goCalendarBack} className="secondary-btn disabled:cursor-not-allowed disabled:opacity-40" aria-label="Previous 35 days"><ChevronLeft size={16} />Previous</button>\n              <button type="button" onClick={goCalendarToday} className="secondary-btn">Today</button>\n              <button type="button" disabled={!canGoForward} onClick={goCalendarForward} className="secondary-btn disabled:cursor-not-allowed disabled:opacity-40" aria-label="Next 35 days">Next<ChevronRight size={16} /></button>\n              \n            </div>\n            <p className="text-xs font-black uppercase tracking-[.12em] text-slate-400">{signedRole} opportunities</p>\n            <h2 className="mt-1 text-2xl font-black text-[#002757]">{calendarRangeLabel}</h2>\n          </div>\n        </div>\n\n        <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs font-extrabold text-slate-600">\n          <span className="inline-flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#4285F4]" />Open shifts</span>\n          <span className="inline-flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#34A853]" />Interested</span>\n          <span className="inline-flex items-center gap-1.5"><span className="grid h-3 w-3 place-items-center rounded-full bg-[#002757] text-[8px] text-white">✓</span>Booked</span>\n        </div>'''

new_header = '''        <div>\n          <p className="text-xs font-black uppercase tracking-[.12em] text-slate-400">{signedRole} opportunities</p>\n          <h2 className="mt-1 text-2xl font-black text-[#002757]">{calendarRangeLabel}</h2>\n        </div>\n\n        <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs font-extrabold text-slate-600">\n          <span className="inline-flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#4285F4]" />Open shifts</span>\n          <span className="inline-flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#34A853]" />Interested</span>\n          <span className="inline-flex items-center gap-1.5"><span className="grid h-3 w-3 place-items-center rounded-full bg-[#002757] text-[8px] text-white">✓</span>Booked</span>\n        </div>\n\n        <div className="mt-4 flex flex-wrap items-center gap-2">\n          <button type="button" disabled={!canGoBack} onClick={goCalendarBack} className="secondary-btn disabled:cursor-not-allowed disabled:opacity-40" aria-label="Previous 35 days"><ChevronLeft size={16} />Previous</button>\n          <button type="button" onClick={goCalendarToday} className="secondary-btn">Today</button>\n          <button type="button" disabled={!canGoForward} onClick={goCalendarForward} className="secondary-btn disabled:cursor-not-allowed disabled:opacity-40" aria-label="Next 35 days">Next<ChevronRight size={16} /></button>\n          <button type="button" onClick={() => setAvailabilityOpen(true)} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-[#04A62F] px-4 py-2 text-sm font-black text-white shadow-sm transition hover:bg-[#038c28] focus:outline-none focus:ring-2 focus:ring-[#04A62F]/30"><CalendarDays size={18} />Post Availability</button>\n          <button type="button" onClick={() => { window.localStorage.setItem("dentalshift_portal_role", "professional"); window.location.href = "/classifieds?post=professional"; }} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-[#002757] px-4 py-2 text-sm font-black text-white shadow-sm transition hover:bg-[#001f46] focus:outline-none focus:ring-2 focus:ring-[#002757]/25"><BriefcaseBusiness size={18} />Post a Position</button>\n        </div>'''

if old_header not in text:
    raise SystemExit('Professional calendar header block not found')
text = text.replace(old_header, new_header, 1)

path.write_text(text)
print('Aligned Professional Portal calendar navigation and posting actions')
