from pathlib import Path

p=Path('lib/dentalshift.ts')
s=p.read_text()
s=s.replace('''offices: { name: string; city: string; province: string; website: string | null; software: string[] | null; google_place_id: string | null; latitude: number | null; longitude: number | null } | null;''','''offices: { name: string; city: string; province: string; website: string | null; software: string[] | null; google_place_id: string | null; latitude: number | null; longitude: number | null; languages: string[] | null; parking_info: string | null; operatories: number | null; benefits: string | null } | null;''')
s=s.replace('''offices(name,city,province,website,software,google_place_id,latitude,longitude)''','''offices(name,city,province,website,software,google_place_id,latitude,longitude,languages,parking_info,operatories,benefits)''')
p.write_text(s)

p=Path('components/WorkflowWorkspaceV2.tsx')
s=p.read_text()
old='''<div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-200/70 pt-3"><div className="flex flex-wrap gap-2 text-[11px] font-bold text-slate-500">{shift.offices?.software?.length ? <span className="rounded-full bg-white/80 px-2 py-1">Office software: {shift.offices.software.join(", ")}</span> : null}{shift.notes && <span className="rounded-full bg-white/80 px-2 py-1">Shift notes available</span>}</div><button type="button" onClick={() => setExpanded((value) => !value)} className="secondary-btn px-3 py-1.5 text-xs">{expanded ? "Hide details" : "Details"}</button></div>'''
new='''<div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-slate-200/70 pt-3"><div className="flex min-w-0 flex-wrap gap-1.5 text-[10px] font-bold text-slate-600">{shift.offices?.software?.length ? <span className="rounded-full bg-slate-50 px-2 py-1">💻 {shift.offices.software.slice(0, 2).join(", ")}</span> : null}{shift.offices?.languages?.length ? <span className="rounded-full bg-slate-50 px-2 py-1">◉ {shift.offices.languages.slice(0, 2).join(", ")}</span> : null}{shift.offices?.operatories ? <span className="rounded-full bg-slate-50 px-2 py-1">{shift.offices.operatories} operatories</span> : null}{shift.offices?.parking_info ? <span className="rounded-full bg-slate-50 px-2 py-1">P Parking</span> : null}{shift.notes && <span className="rounded-full bg-slate-50 px-2 py-1">Shift notes</span>}</div><button type="button" onClick={() => setExpanded((value) => !value)} className="secondary-btn shrink-0 px-3 py-1.5 text-xs">{expanded ? "Hide details" : "More"}</button></div>'''
if old not in s: raise SystemExit('compact details row anchor not found')
s=s.replace(old,new,1)
old='''{expanded && <div className="mt-3 rounded-xl border border-slate-200 bg-white/80 p-3"><div className="grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Office software</p><p className="mt-1 font-extrabold text-[#002757]">{shift.offices?.software?.length ? shift.offices.software.join(", ") : "Not listed by office"}</p>{shift.required_software && <p className="mt-1 text-xs font-semibold text-slate-500">Shift requirement: {shift.required_software}</p>}</div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Shift notes</p><p className="mt-1 font-semibold text-slate-700">{shift.notes || "No additional notes provided."}</p></div></div><p className="mt-3 text-xs font-semibold text-slate-500"><ShieldCheck size={14} className="mr-1 inline text-[#34A853]" />Office contact information remains protected until booking confirmation.</p></div>}'''
new='''{expanded && <div className="mt-3 rounded-xl border border-slate-200 bg-white/80 p-3"><div className="grid gap-x-4 gap-y-2 text-xs sm:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Office setup</p><p className="mt-1 font-extrabold text-[#002757]">{shift.offices?.operatories ? `${shift.offices.operatories} operatories` : "Size not listed"}{shift.offices?.software?.length ? ` · ${shift.offices.software.join(", ")}` : ""}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Languages</p><p className="mt-1 font-extrabold text-[#002757]">{shift.offices?.languages?.length ? shift.offices.languages.join(", ") : "Not listed"}</p></div>{shift.offices?.parking_info && <div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Parking</p><p className="mt-1 font-semibold text-slate-700">{shift.offices.parking_info}</p></div>}{shift.offices?.benefits && <div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Office highlights</p><p className="mt-1 font-semibold text-slate-700">{shift.offices.benefits}</p></div>}<div className="sm:col-span-2"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Shift notes</p><p className="mt-1 font-semibold text-slate-700">{shift.notes || "No additional notes provided."}</p>{shift.required_software && <p className="mt-1 font-semibold text-slate-500">Required software: {shift.required_software}</p>}</div></div><p className="mt-2 text-[11px] font-semibold text-slate-500"><ShieldCheck size={13} className="mr-1 inline text-[#34A853]" />Contact information stays protected until booking.</p></div>}'''
if old not in s: raise SystemExit('expanded details anchor not found')
s=s.replace(old,new,1)
p.write_text(s)
print('Enriched professional Dental Office card with compact office information.')