from pathlib import Path

# Update available professional card component
panel = Path('components/AnonymousAvailableStaffPanel.tsx')
text = panel.read_text()
text = text.replace('''  preferred?: boolean;\n};''','''  preferred?: boolean;\n  interested?: boolean;\n  interestApplicationId?: string | null;\n  interestElapsed?: string | null;\n  licenceProvince?: string | null;\n  requestedRate?: number | null;\n};''')
text = text.replace('''export function AnonymousAvailableStaffPanel({\n  staff,\n}: {\n  staff: AnonymousAvailableStaff[];\n}) {''','''export function AnonymousAvailableStaffPanel({\n  staff,\n  onBookInterest,\n  busyApplicationId,\n}: {\n  staff: AnonymousAvailableStaff[];\n  onBookInterest?: (applicationId: string) => void;\n  busyApplicationId?: string | null;\n}) {''')
old_article = '''          {items.map((item) => <article key={item.id} className="p-3">\n            <div className="flex items-center justify-between gap-3">\n              <div>\n                <strong className="text-sm text-[#032757]">{item.role} available</strong>\n                <p className="mt-1 text-xs font-bold text-slate-500">{shortTime(item.startsAt)}–{shortTime(item.endsAt)}{item.minimumHourlyRate != null ? ` · Min $${item.minimumHourlyRate.toFixed(2)}/hr` : ""}</p>\n              </div>\n              <span className="flex shrink-0 items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-black text-slate-600">\n                <MapPin size={12} />{item.distanceKm == null ? "Distance unavailable" : `${item.distanceKm.toFixed(1)} km`}\n              </span>\n            </div>\n          </article>)}'''
new_article = '''          {items.map((item) => <article key={item.id} className={`p-3 ${item.interested ? "bg-[#f3fbf5]" : ""}`}>\n            <div className="flex items-center justify-between gap-3">\n              <div>\n                <strong className="text-sm text-[#032757]">{item.role} available</strong>\n                <p className="mt-1 text-xs font-bold text-slate-500">{shortTime(item.startsAt)}–{shortTime(item.endsAt)}{item.minimumHourlyRate != null ? ` · Min $${item.minimumHourlyRate.toFixed(2)}/hr` : ""}</p>\n              </div>\n              <span className="flex shrink-0 items-center gap-1 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-black text-slate-600">\n                <MapPin size={12} />{item.distanceKm == null ? "Distance unavailable" : `${item.distanceKm.toFixed(1)} km`}\n              </span>\n            </div>\n            {item.interested && <div className="mt-3 border-t border-[#34A853]/25 pt-3">\n              <div className="flex items-center justify-between gap-2">\n                <span className="text-xs font-black text-[#017f27]">✓ I’m Interested</span>\n                {item.interestElapsed && <span className="font-mono text-xs font-black tabular-nums text-[#017f27]">{item.interestElapsed}</span>}\n              </div>\n              <div className="mt-3 grid grid-cols-2 gap-x-2 gap-y-1 text-[11px] text-slate-600">\n                <span>Licence province: <strong>{item.licenceProvince || "Unavailable"}</strong></span>\n                <span>Completed: <strong>{item.completedShifts || 0}</strong></span>\n                <span>Rating: <strong>{item.rating ? `${item.rating}★` : "No rating yet"}</strong></span>\n                <span>Reliability: <strong>{item.reliabilityScore != null ? `${item.reliabilityScore}%` : "Not enough history"}</strong></span>\n                <span className="col-span-2">Requested rate: <strong>{item.requestedRate != null ? `$${item.requestedRate.toFixed(2)}/hr` : "Not specified"}</strong></span>\n              </div>\n              <p className="mt-2 text-[10px] leading-4 text-slate-500">Identity and contact details are shared after booking confirmation.</p>\n              {item.interestApplicationId && onBookInterest && <button type="button" disabled={busyApplicationId === item.interestApplicationId} onClick={() => onBookInterest(item.interestApplicationId!)} className="primary-btn mt-2 w-full justify-center py-2 text-xs">{busyApplicationId === item.interestApplicationId ? "Booking…" : "✓ Book Now"}</button>}\n            </div>}\n          </article>)}'''
if old_article not in text:
    raise SystemExit('Available professional article block not found')
text = text.replace(old_article, new_article, 1)
panel.write_text(text)

# Update office workspace: remove applicant card and enrich available-professional cards
path = Path('components/OfficeWorkspaceV2.tsx')
text = path.read_text()
old_applicants = '''                {pendingPairings.length > 0 && <section className="mt-3"><h4 className="mb-2 flex items-center gap-2 text-base font-black text-[#017f27]"><span className="h-3 w-3 rounded-full bg-[#34A853]" />Applicants</h4><div className="space-y-2">{pendingPairings.map((application) => { const profile = application.professional_profiles; return <div key={application.id} className="rounded-xl border-2 border-[#34A853]/65 bg-[#f0fbf3] p-1 shadow-[0_8px_22px_rgba(52,168,83,0.10)]"><div className="rounded-lg bg-white p-3"><div className="mb-2 flex items-center justify-between gap-2 rounded-lg bg-[#eaf8ee] px-2.5 py-2"><span className="text-xs font-black text-[#017f27]">✓ I’m Interested</span><span className="font-mono text-xs font-black tabular-nums text-[#017f27]">{interestElapsed(application.created_at, nowMs)}</span></div><h5 className="font-black text-[#032757]">{profile?.profession || shift.profession}</h5><p className="mt-1 text-[11px] font-bold text-[#017f27]">{profile?.licence_province ? `Licence province: ${profile.licence_province}` : "Credential status unavailable"}</p><div className="mt-2 grid grid-cols-2 gap-x-2 gap-y-1 text-[11px] text-slate-600"><span>Rating: <strong>{profile?.rating ? `${profile.rating}★` : "No rating yet"}</strong></span><span>Completed: <strong>{profile?.completed_shifts || 0}</strong></span><span>Reliability: <strong>{profile?.reliability_score != null ? `${profile.reliability_score}%` : "Not enough history"}</strong></span><span>Requested rate: <strong>{application.proposed_rate != null ? `$${Number(application.proposed_rate).toFixed(2)}/hr` : "Not specified"}</strong></span></div><p className="mt-2 text-[10px] leading-4 text-slate-500">Identity and contact details are shared after booking confirmation.</p><button disabled={busy === application.id} onClick={() => void act(application.id, () => acceptApplication(application.id))} className="primary-btn mt-2 w-full justify-center py-2 text-xs"><Check size={15} />{busy === application.id ? "Booking…" : "Book Now"}</button></div></div>; })}</div></section>}\n'''
if old_applicants not in text:
    raise SystemExit('Applicant box block not found')
text = text.replace(old_applicants, '', 1)

old_anonymous = '''  const anonymousStaff: AnonymousAvailableStaff[] = selectedAvailability.map((slot) => {\n    const profile = slot.professional_profiles;\n    const completed = Number(profile?.completed_shifts || 0);\n    const localAnesthetic = Boolean(profile?.local_anesthetic) && roleCode(profile?.profession) === "RDH";\n    return {\n      id: slot.professional_id,\n      role: roleCode(profile?.profession),\n      profession: profile?.profession || "Dental professional",\n      minimumHourlyRate: Number(slot.hourly_rate),\n      distanceKm: distanceForSlot(slot),\n      startsAt: slot.starts_at,\n      endsAt: slot.ends_at,\n      yearsExperience: profile?.years_experience ?? null,\n      rating: Number(profile?.rating || 0) > 0 ? Number(profile?.rating) : null,\n      completedShifts: completed,\n      reliabilityScore: completed > 0 && profile?.reliability_score != null ? Number(profile.reliability_score) : null,\n      cancellations: null,\n      skills: profile?.skills || null,\n      software: profile?.skills || null,\n      qualifications: localAnesthetic ? [{ label: "Local Anesthetic", verified: profile?.local_anesthetic_status === "verified" }] : [],\n      preferred: data.preferredProfessionals.some((person) => person.matched_professional_id === slot.professional_id),\n    };\n  });'''
new_anonymous = '''  const applicantByProfessional = new Map(selectedShifts.flatMap((shift) => (shift.applications || []).filter((application) => application.status === "applied").map((application) => [application.professional_id, application] as const)));\n  const anonymousStaff: AnonymousAvailableStaff[] = selectedAvailability.map((slot) => {\n    const profile = slot.professional_profiles;\n    const completed = Number(profile?.completed_shifts || 0);\n    const localAnesthetic = Boolean(profile?.local_anesthetic) && roleCode(profile?.profession) === "RDH";\n    const interest = applicantByProfessional.get(slot.professional_id);\n    return {\n      id: slot.professional_id,\n      role: roleCode(profile?.profession),\n      profession: profile?.profession || "Dental professional",\n      minimumHourlyRate: Number(slot.hourly_rate),\n      distanceKm: distanceForSlot(slot),\n      startsAt: slot.starts_at,\n      endsAt: slot.ends_at,\n      yearsExperience: profile?.years_experience ?? null,\n      rating: Number(profile?.rating || 0) > 0 ? Number(profile?.rating) : null,\n      completedShifts: completed,\n      reliabilityScore: completed > 0 && profile?.reliability_score != null ? Number(profile.reliability_score) : null,\n      cancellations: null,\n      skills: profile?.skills || null,\n      software: profile?.skills || null,\n      qualifications: localAnesthetic ? [{ label: "Local Anesthetic", verified: profile?.local_anesthetic_status === "verified" }] : [],\n      preferred: data.preferredProfessionals.some((person) => person.matched_professional_id === slot.professional_id),\n      interested: Boolean(interest),\n      interestApplicationId: interest?.id || null,\n      interestElapsed: interest ? interestElapsed(interest.created_at, nowMs) : null,\n      licenceProvince: interest?.professional_profiles?.licence_province || profile?.licence_province || null,\n      requestedRate: interest?.proposed_rate != null ? Number(interest.proposed_rate) : null,\n    };\n  });'''
if old_anonymous not in text:
    raise SystemExit('anonymousStaff mapping not found')
text = text.replace(old_anonymous, new_anonymous, 1)

old_panel = '''<AnonymousAvailableStaffPanel staff={anonymousStaff} />'''
new_panel = '''<AnonymousAvailableStaffPanel staff={anonymousStaff} busyApplicationId={busy || null} onBookInterest={(applicationId) => void act(applicationId, () => acceptApplication(applicationId))} />'''
if old_panel not in text:
    raise SystemExit('AnonymousAvailableStaffPanel call not found')
text = text.replace(old_panel, new_panel, 1)
path.write_text(text)
