from pathlib import Path

path = Path('app/classifieds/page.tsx')
text = path.read_text()

text = text.replace('  const [backHref, setBackHref] = useState("/professionals/find-shifts");', '  const [backHref, setBackHref] = useState("/professionals/find-shifts");\n  const [portalRole, setPortalRole] = useState<"office" | "professional" | null>(null);')
text = text.replace('    const portalRole = window.localStorage.getItem("dentalshift_portal_role");\n    setBackHref(portalRole === "office" ? "/office/overview" : "/professionals/find-shifts");', '    const storedRole = window.localStorage.getItem("dentalshift_portal_role");\n    const normalizedRole = storedRole === "office" ? "office" : storedRole === "professional" ? "professional" : null;\n    setPortalRole(normalizedRole);\n    setBackHref(normalizedRole === "office" ? "/office/overview" : "/professionals/find-shifts");')

old = '<div className="grid gap-4 md:grid-cols-2"><button type="button" onClick={() => setPostingKind("office")} className={`rounded-2xl border p-5 text-left transition ${postingKind === "office" ? "border-[#002757] bg-[#edf3fa] ring-2 ring-[#002757]/10" : "border-slate-200 bg-white hover:border-[#002757]/35"}`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#002757] text-white"><Building2 size={21} /></span><div><h3 className="font-black text-[#002757]">Dental Office</h3><p className="text-sm text-slate-500">Post a Position</p></div></div></button><button type="button" onClick={() => setPostingKind("professional")} className={`rounded-2xl border p-5 text-left transition ${postingKind === "professional" ? "border-[#01A32E] bg-[#eaf8ee] ring-2 ring-[#01A32E]/10" : "border-slate-200 bg-white hover:border-[#01A32E]/35"}`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#01A32E] text-white"><UserRound size={21} /></span><div><h3 className="font-black text-[#002757]">Dental Professional</h3><p className="text-sm text-slate-500">Looking for an Office</p></div></div></button></div>'
new = '<div className={`grid gap-4 ${portalRole === "office" || portalRole === "professional" ? "md:grid-cols-1" : "md:grid-cols-2"}`}>{portalRole !== "professional" && <button type="button" onClick={() => setPostingKind("office")} className={`rounded-2xl border p-5 text-left transition ${postingKind === "office" ? "border-[#002757] bg-[#edf3fa] ring-2 ring-[#002757]/10" : "border-slate-200 bg-white hover:border-[#002757]/35"}`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#002757] text-white"><Building2 size={21} /></span><div><h3 className="font-black text-[#002757]">Dental Office</h3><p className="text-sm text-slate-500">Post a Position</p></div></div></button>}{portalRole !== "office" && <button type="button" onClick={() => setPostingKind("professional")} className={`rounded-2xl border p-5 text-left transition ${postingKind === "professional" ? "border-[#01A32E] bg-[#eaf8ee] ring-2 ring-[#01A32E]/10" : "border-slate-200 bg-white hover:border-[#01A32E]/35"}`}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#01A32E] text-white"><UserRound size={21} /></span><div><h3 className="font-black text-[#002757]">Dental Professional</h3><p className="text-sm text-slate-500">Looking for an Office</p></div></div></button>}</div>'

if old not in text:
    raise RuntimeError('Posting choice block not found')
text = text.replace(old, new)

text = text.replace('  const [postingKind, setPostingKind] = useState<"office" | "professional">("office");', '  const [postingKind, setPostingKind] = useState<"office" | "professional">("office");\n\n  useEffect(() => {\n    if (portalRole === "professional") setPostingKind("professional");\n    if (portalRole === "office") setPostingKind("office");\n  }, [portalRole]);')

path.write_text(text)
print('Office/professional DentalJobs posting choices are now role-aware.')
