from pathlib import Path

def replace_once(s, old, new, label):
    if old not in s:
        raise SystemExit(f'{label} pattern not found')
    return s.replace(old, new, 1)

p = Path('components/WorkflowWorkspaceV2.tsx')
s = p.read_text()
s = replace_once(s, 'function longDate(value: string) {\n  return new Date(`${value}T12:00:00`).toLocaleDateString("en-CA", { weekday: "long", month: "long", day: "numeric" });\n}\n', 'function longDate(value: string) {\n  return new Date(`${value}T12:00:00`).toLocaleDateString("en-CA", { weekday: "long", month: "long", day: "numeric" });\n}\n\nfunction interestAge(createdAt: string, now: number) {\n  const elapsed = Math.max(0, now - new Date(createdAt).getTime());\n  const day = Math.floor(elapsed / 86400000) + 1;\n  const hours = Math.floor((elapsed % 86400000) / 3600000);\n  const minutes = Math.floor((elapsed % 3600000) / 60000);\n  return `Day ${day} · ${hours}h ${minutes}m`;\n}\n', 'professional timer helper')
s = replace_once(s, '  const [availabilityModalOpen, setAvailabilityModalOpen] = useState(false);\n', '  const [availabilityModalOpen, setAvailabilityModalOpen] = useState(false);\n  const [pairingNow, setPairingNow] = useState(() => Date.now());\n', 'professional timer state')
s = replace_once(s, '  useEffect(() => { void refresh(); }, [userId, refreshKey]);\n', '  useEffect(() => { void refresh(); }, [userId, refreshKey]);\n  useEffect(() => { const timer = window.setInterval(() => setPairingNow(Date.now()), 60000); return () => window.clearInterval(timer); }, []);\n', 'professional timer effect')
s = s.replace('{dayBookings.length > 1 ? `${dayBookings.length} booked` : "Booked"}', '{dayBookings.length > 1 ? `${dayBookings.length} BOOKED` : "BOOKED"}')
old = '                  <div className="mt-3">{application ? <span className="inline-flex rounded-full bg-white px-2.5 py-1 text-[11px] font-extrabold text-[#002757]">{application.status.replace("_", " ")}</span> : <button type="button" disabled={busy === `apply-${shift.id}`} onClick={() => void act(`apply-${shift.id}`, () => applyForShift({ shiftId: shift.id, professionalId: userId }))} className="primary-btn w-full justify-center">{busy === `apply-${shift.id}` ? "Saving…" : "I’m Interested"}</button>}</div>'
new = '                  <div className="mt-3">{application ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-black text-amber-900">{application.status === "invited" ? "Office interested — waiting for you" : "You’re interested — waiting for office"}</p><p className="mt-1 text-[11px] font-extrabold text-amber-700">Interest open · {interestAge(application.created_at, pairingNow)}</p>{application.status === "invited" && <button type="button" disabled={busy === application.id} onClick={() => void act(application.id, () => respondToInvitation(application.id, true))} className="primary-btn mt-2 w-full justify-center">{busy === application.id ? "Booking…" : "I’m Interested"}</button>}</div> : <button type="button" disabled={busy === `apply-${shift.id}`} onClick={() => void act(`apply-${shift.id}`, () => applyForShift({ shiftId: shift.id, professionalId: userId }))} className="primary-btn w-full justify-center">{busy === `apply-${shift.id}` ? "Saving…" : "I’m Interested"}</button>}</div>'
s = replace_once(s, old, new, 'professional pairing card')
s = s.replace('<Chip tone="green">Booked</Chip>', '<Chip tone="green">BOOKED</Chip>')
p.write_text(s)

p = Path('components/OfficeWorkspaceV2.tsx')
s = p.read_text()
s = replace_once(s, 'function longDate(value: string) {\n  return new Date(`${value}T12:00:00`).toLocaleDateString("en-CA", { weekday: "long", month: "long", day: "numeric" });\n}\n', 'function longDate(value: string) {\n  return new Date(`${value}T12:00:00`).toLocaleDateString("en-CA", { weekday: "long", month: "long", day: "numeric" });\n}\n\nfunction interestAge(createdAt: string, now: number) {\n  const elapsed = Math.max(0, now - new Date(createdAt).getTime());\n  const day = Math.floor(elapsed / 86400000) + 1;\n  const hours = Math.floor((elapsed % 86400000) / 3600000);\n  const minutes = Math.floor((elapsed % 3600000) / 60000);\n  return `Day ${day} · ${hours}h ${minutes}m`;\n}\n', 'office timer helper')
s = replace_once(s, '  const [selectedDate, setSelectedDate] = useState(() => localDateKey(new Date()));\n', '  const [selectedDate, setSelectedDate] = useState(() => localDateKey(new Date()));\n  const [pairingNow, setPairingNow] = useState(() => Date.now());\n', 'office timer state')
s = replace_once(s, '  useEffect(() => { void refresh(); }, [office.id, refreshKey]);\n', '  useEffect(() => { void refresh(); }, [office.id, refreshKey]);\n  useEffect(() => { const timer = window.setInterval(() => setPairingNow(Date.now()), 60000); return () => window.clearInterval(timer); }, []);\n', 'office timer effect')
s = s.replace('{dayBookings.length} booked</div>', '{dayBookings.length === 1 ? "BOOKED" : `${dayBookings.length} BOOKED`}</div>')
s = replace_once(s, '              const applicants = (shift.applications || []).filter((application) => application.status === "applied");\n', '              const applicants = (shift.applications || []).filter((application) => application.status === "applied");\n              const pendingPairings = (shift.applications || []).filter((application) => application.status === "applied" || application.status === "invited");\n', 'office pairing list')
old = '                <div className="mt-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Applicants ({applicants.length})</p>{applicants.length === 0 ? <p className="mt-2 text-xs text-slate-500">No applications yet.</p> : <div className="mt-2 space-y-2">{applicants.map((application) => <div key={application.id} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-600">Verified {application.professional_profiles?.profession || "professional"} · {application.professional_profiles?.licence_province || ""}</p><button disabled={busy === application.id} onClick={() => void act(application.id, () => acceptApplication(application.id))} className="primary-btn mt-2 w-full justify-center"><Check size={15} />{busy === application.id ? "Confirming…" : "Confirm professional"}</button></div>)}</div>}</div>'
new = '                <div className="mt-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Pairings ({pendingPairings.length})</p>{pendingPairings.length === 0 ? <p className="mt-2 text-xs text-slate-500">No interest pairings yet.</p> : <div className="mt-2 space-y-2">{pendingPairings.map((application) => <div key={application.id} className="rounded-xl border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-bold text-slate-700">Verified {application.professional_profiles?.profession || "professional"} · {application.professional_profiles?.licence_province || ""}</p><p className="mt-2 text-xs font-black text-amber-900">{application.status === "applied" ? "Professional interested — waiting for you" : "You’re interested — waiting for professional"}</p><p className="mt-1 text-[11px] font-extrabold text-amber-700">Interest open · {interestAge(application.created_at, pairingNow)}</p>{application.status === "applied" && <button disabled={busy === application.id} onClick={() => void act(application.id, () => acceptApplication(application.id))} className="primary-btn mt-2 w-full justify-center"><Check size={15} />{busy === application.id ? "Booking…" : "I’m Interested"}</button>}</div>)}</div>}</div>'
s = replace_once(s, old, new, 'office pairing cards')
s = s.replace('<strong className="text-[#032757]">Confirmed booking</strong>', '<strong className="text-[#032757]">BOOKED</strong>')
p.write_text(s)
