from pathlib import Path

path = Path('app/classifieds/page.tsx')
text = path.read_text()

old = '''        <div className={`mt-6 grid gap-4 ${portalRole ? "max-w-2xl" : "lg:grid-cols-2"}`}>
          {portalRole !== "professional" && <div className="relative overflow-hidden rounded-2xl border-2 border-[#002757] bg-[#002757] p-5 shadow-xl transition hover:border-[#01A32E] hover:shadow-2xl"><div className="absolute inset-x-0 top-0 h-1.5 bg-[#01A32E]" /><button type="button" onClick={() => { setImportPrefill(null); setEditingListing(null); setPostingMode("office"); setSubmitted(false); setPosted(false); setPublishError(""); }} className="group block w-full text-left"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#01A32E] text-white shadow-md ring-4 ring-white/10"><Building2 size={24} /></span><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9be3ad]">Dental Office</p><h2 className="mt-1 text-xl font-black text-white">Post a Position</h2><p className="mt-2 text-sm leading-6 text-slate-200">Advertise an opening anonymously. Your office name, exact address and contact information stay private.</p><span className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#01A32E] px-4 py-2.5 text-sm font-black text-white shadow-md transition group-hover:bg-white group-hover:text-[#002757]">Create office posting <BriefcaseBusiness size={16} /></span></div></div></button><div className="mt-5 border-t border-white/15 pt-4"><p className="text-xs leading-5 text-slate-300">Already posted on Indeed or another job site? Paste your existing ad and we’ll fill in the details for you.</p><button type="button" onClick={() => { setImportAdText(""); setImportError(""); setImportingOfficeAd(true); }} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-white/25 bg-white px-4 py-2.5 text-sm font-black text-[#002757] shadow-sm transition hover:border-[#01A32E] hover:bg-[#effaf2] sm:w-auto"><FileText size={16} /> Import Existing Job Ad</button></div></div>}
          {portalRole !== "office" && <button type="button" onClick={() => { setEditingListing(null); setPostingMode("professional"); setSubmitted(false); setPosted(false); setPublishError(""); }} className="group rounded-2xl border-2 border-[#01A32E]/20 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#01A32E] hover:shadow-md"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#01A32E] text-white"><UserRound size={24} /></span><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#017f27]">Dental Professional</p><h2 className="mt-1 text-xl font-black text-slate-900">Looking for an Office</h2><p className="mt-2 text-sm leading-6 text-slate-600">Advertise what you are looking for without displaying your identity. Your résumé/CV already on file can be used when you apply.</p><span className="mt-3 inline-flex items-center gap-2 text-sm font-black text-[#01A32E]">Create professional posting <FileText size={16} /></span></div></div></button>}
        </div>'''

new = '''        {portalRole === "office" ? <div className="mt-6 grid items-stretch gap-4 md:grid-cols-3">
          <button type="button" onClick={() => { setImportPrefill(null); setEditingListing(null); setPostingMode("office"); setSubmitted(false); setPosted(false); setPublishError(""); }} className="group relative flex h-full min-h-[230px] flex-col overflow-hidden rounded-2xl border-2 border-[#002757] bg-[#002757] p-5 text-left shadow-xl transition hover:-translate-y-0.5 hover:border-[#01A32E] hover:shadow-2xl"><div className="absolute inset-x-0 top-0 h-1.5 bg-[#01A32E]" /><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#01A32E] text-white shadow-md ring-4 ring-white/10"><Building2 size={24} /></span><div className="mt-4 flex flex-1 flex-col"><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9be3ad]">Dental Office</p><h2 className="mt-1 text-xl font-black text-white">Post a Position</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-200">Create a new anonymous DentalJobs posting from scratch.</p><span className="mt-4 inline-flex w-fit items-center gap-2 rounded-xl bg-[#01A32E] px-4 py-2.5 text-sm font-black text-white shadow-md transition group-hover:bg-white group-hover:text-[#002757]">Create Posting <BriefcaseBusiness size={16} /></span></div></button>

          <button type="button" onClick={() => { setImportAdText(""); setImportError(""); setImportingOfficeAd(true); }} className="group flex h-full min-h-[230px] flex-col rounded-2xl border-2 border-[#01A32E]/35 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#01A32E] hover:shadow-md"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#01A32E] text-white"><FileText size={24} /></span><div className="mt-4 flex flex-1 flex-col"><p className="text-xs font-black uppercase tracking-[0.12em] text-[#017f27]">Already advertising?</p><h2 className="mt-1 text-xl font-black text-[#002757]">Import Existing Job Ad</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">Paste an ad from Indeed or another job site and DentalShift will fill the posting form for you.</p><span className="mt-4 inline-flex w-fit items-center gap-2 rounded-xl bg-[#002757] px-4 py-2.5 text-sm font-black text-white shadow-sm transition group-hover:bg-[#01A32E]">Import Job Ad <FileText size={16} /></span></div></button>

          <button type="button" onClick={() => document.getElementById("my-dentaljobs")?.scrollIntoView({ behavior: "smooth", block: "start" })} className="group flex h-full min-h-[230px] flex-col rounded-2xl border-2 border-[#002757]/15 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#002757] hover:shadow-md"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#002757] text-white"><BriefcaseBusiness size={24} /></span><div className="mt-4 flex flex-1 flex-col"><p className="text-xs font-black uppercase tracking-[0.12em] text-[#4285F4]">Office Postings</p><h2 className="mt-1 text-xl font-black text-[#002757]">My DentalJobs</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-600">Review, edit, pause, renew or close your current and previous job ads.</p><span className="mt-4 inline-flex w-fit items-center gap-2 text-sm font-black text-[#002757]">Manage {myOfficeJobs.length} Posting{myOfficeJobs.length === 1 ? "" : "s"} <ChevronLeft size={16} className="rotate-[-90deg]" /></span></div></button>
        </div> : <div className={`mt-6 grid gap-4 ${portalRole ? "max-w-2xl" : "lg:grid-cols-2"}`}>
          {portalRole !== "professional" && <button type="button" onClick={() => { setImportPrefill(null); setEditingListing(null); setPostingMode("office"); setSubmitted(false); setPosted(false); setPublishError(""); }} className="group relative overflow-hidden rounded-2xl border-2 border-[#002757] bg-[#002757] p-5 text-left shadow-xl transition hover:-translate-y-1 hover:border-[#01A32E] hover:shadow-2xl"><div className="absolute inset-x-0 top-0 h-1.5 bg-[#01A32E]" /><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#01A32E] text-white shadow-md ring-4 ring-white/10"><Building2 size={24} /></span><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#9be3ad]">Dental Office</p><h2 className="mt-1 text-xl font-black text-white">Post a Position</h2><p className="mt-2 text-sm leading-6 text-slate-200">Advertise an opening anonymously. Your office name, exact address and contact information stay private.</p><span className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#01A32E] px-4 py-2.5 text-sm font-black text-white shadow-md transition group-hover:bg-white group-hover:text-[#002757]">Create office posting <BriefcaseBusiness size={16} /></span></div></div></button>}
          {portalRole !== "office" && <button type="button" onClick={() => { setEditingListing(null); setPostingMode("professional"); setSubmitted(false); setPosted(false); setPublishError(""); }} className="group rounded-2xl border-2 border-[#01A32E]/20 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#01A32E] hover:shadow-md"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-[#01A32E] text-white"><UserRound size={24} /></span><div><p className="text-xs font-black uppercase tracking-[0.12em] text-[#017f27]">Dental Professional</p><h2 className="mt-1 text-xl font-black text-slate-900">Looking for an Office</h2><p className="mt-2 text-sm leading-6 text-slate-600">Advertise what you are looking for without displaying your identity. Your résumé/CV already on file can be used when you apply.</p><span className="mt-3 inline-flex items-center gap-2 text-sm font-black text-[#01A32E]">Create professional posting <FileText size={16} /></span></div></div></button>}
        </div>}'''

if old not in text:
    raise SystemExit('Could not find current DentalJobs action-card block')
text = text.replace(old, new, 1)
text = text.replace('{portalRole === "office" && <section className="relative mt-6', '{portalRole === "office" && <section id="my-dentaljobs" className="relative mt-6 scroll-mt-24', 1)
path.write_text(text)
print('Reorganized office DentalJobs into three equal cards')
