from pathlib import Path

page = Path('app/classifieds/page.tsx')
text = page.read_text()

old = 'portalRole === "office" ? "Applications & Interest" : "Office Interest"'
new = 'portalRole === "office" ? "Dental Professionals Interest" : "Office Interest"'
if old not in text:
    raise SystemExit('connection title anchor not found')
text = text.replace(old, new, 1)

old = 'portalRole === "office" ? "Review professionals who applied and track professionals your office contacted." : "Review dental offices that expressed interest in your DentalJobs ad."'
new = 'portalRole === "office" ? "Review dental professionals who applied or expressed interest in your DentalJobs postings." : "Review dental offices that expressed interest in your DentalJobs ad."'
if old not in text:
    raise SystemExit('connection subtitle anchor not found')
text = text.replace(old, new, 1)

old = '''{portalRole === "office" && item.candidatePreview && <div className="mt-3 max-w-2xl rounded-2xl border border-[#4285F4]/20 bg-[#f7faff] p-4"><div className="flex items-center gap-2"><FileText size={16} className="text-[#4285F4]"/><p className="text-xs font-black uppercase tracking-[0.12em] text-[#4285F4]">Candidate Preview</p></div><p className="mt-2 text-sm font-bold leading-6 text-[#002757]">{item.candidatePreview.summary}</p><div className="mt-3 flex flex-wrap gap-2">{item.candidatePreview.yearsExperience != null && <span className="rounded-lg bg-white px-2.5 py-1.5 text-xs font-black text-slate-600 ring-1 ring-slate-200">{item.candidatePreview.yearsExperience} yrs experience</span>}{item.candidatePreview.skills.slice(0,4).map((skill) => <span key={skill} className="rounded-lg bg-white px-2.5 py-1.5 text-xs font-black text-slate-600 ring-1 ring-slate-200">{skill}</span>)}{item.candidatePreview.software.slice(0,3).map((software) => <span key={software} className="rounded-lg bg-[#eef4ff] px-2.5 py-1.5 text-xs font-black text-[#245FB8]">{software}</span>)}</div>{item.candidatePreview.certifications.length > 0 && <p className="mt-3 text-xs font-bold text-[#017f27]">Qualifications: {item.candidatePreview.certifications.join(" · ")}</p>}<p className="mt-3 text-[11px] font-semibold leading-5 text-slate-400">Name, direct contact details, exact address, employer names and the original résumé are withheld before candidate unlock.</p></div>}'''
new = '''{portalRole === "office" && item.candidatePreview && <div className="mt-3 max-w-2xl rounded-2xl border border-[#4285F4]/20 bg-[#f7faff] p-4"><div className="flex items-center gap-2"><UserRound size={17} className="text-[#002757]"/><p className="font-black text-[#002757]">Dental Professional</p></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-white p-3 ring-1 ring-slate-200"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Location</p><p className="mt-1 text-sm font-bold text-[#002757]">{[item.candidatePreview.safeCity || item.city, item.candidatePreview.safeProvince || item.province].filter(Boolean).join(", ") || "Not specified"}</p></div><div className="rounded-xl bg-white p-3 ring-1 ring-slate-200"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Profession</p><p className="mt-1 text-sm font-bold text-[#002757]">{item.candidatePreview.profession || item.profession || "Dental Professional"}</p></div><div className="rounded-xl bg-white p-3 ring-1 ring-slate-200"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Employment</p><p className="mt-1 text-sm font-bold text-[#002757]">{item.employment || "Not specified"}</p></div><div className="rounded-xl bg-white p-3 ring-1 ring-slate-200"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Experience</p><p className="mt-1 text-sm font-bold text-[#002757]">{item.candidatePreview.yearsExperience != null ? `${item.candidatePreview.yearsExperience} year${item.candidatePreview.yearsExperience === 1 ? "" : "s"}` : "Not specified"}</p></div></div>{item.candidatePreview.summary && <p className="mt-3 rounded-xl bg-white p-3 text-sm font-semibold leading-6 text-slate-600 ring-1 ring-slate-200">{item.candidatePreview.summary}</p>}{(item.candidatePreview.skills.length > 0 || item.candidatePreview.software.length > 0 || item.candidatePreview.certifications.length > 0) && <div className="mt-3 flex flex-wrap gap-2">{item.candidatePreview.skills.slice(0,4).map((skill) => <span key={skill} className="rounded-lg bg-white px-2.5 py-1.5 text-xs font-black text-slate-600 ring-1 ring-slate-200">{skill}</span>)}{item.candidatePreview.software.slice(0,3).map((software) => <span key={software} className="rounded-lg bg-[#eef4ff] px-2.5 py-1.5 text-xs font-black text-[#245FB8]">{software}</span>)}{item.candidatePreview.certifications.slice(0,3).map((certification) => <span key={certification} className="rounded-lg bg-[#eaf8ee] px-2.5 py-1.5 text-xs font-black text-[#017f27]">{certification}</span>)}</div>}<p className="mt-3 text-[11px] font-semibold leading-5 text-slate-400">Name, direct contact details, exact address, employer names and the original résumé remain private until candidate unlock.</p></div>}'''
if old not in text:
    raise SystemExit('candidate preview card anchor not found')
text = text.replace(old, new, 1)

page.write_text(text)
print('Restyled office Dental Professionals Interest card')
