from pathlib import Path

path = Path('components/OfficeWorkspaceV2.tsx')
text = path.read_text()
old = '''{pendingPairings.length > 0 && <section className="mt-3 rounded-xl bg-[#F21C13] p-2"><h4 className="mb-2 text-center text-base font-black text-white">Applicants</h4><div className="space-y-2">{pendingPairings.map((application) => { const profile = application.professional_profiles; return <div key={application.id} className="rounded-lg bg-white p-3"><div className="mb-2 flex items-center justify-between gap-2 rounded-lg bg-[#eaf8ee] px-2.5 py-2"><span className="text-xs font-black text-[#017f27]">✓ I’m Interested</span><span className="font-mono text-xs font-black tabular-nums text-[#017f27]">{interestElapsed(application.created_at, nowMs)}</span></div><h5 className="font-black text-[#032757]">{profile?.profession || shift.profession}</h5><p className="mt-1 text-[11px] font-bold text-[#017f27]">{profile?.licence_province ? `Licence province: ${profile.licence_province}` : "Credential status unavailable"}</p><div className="mt-2 grid grid-cols-2 gap-x-2 gap-y-1 text-[11px] text-slate-600"><span>Rating: <strong>{profile?.rating ? `${profile.rating}★` : "No rating yet"}</strong></span><span>Completed: <strong>{profile?.completed_shifts || 0}</strong></span><span>Reliability: <strong>{profile?.reliability_score != null ? `${profile.reliability_score}%` : "Not enough history"}</strong></span><span>Requested rate: <strong>{application.proposed_rate != null ? `$${Number(application.proposed_rate).toFixed(2)}/hr` : "Not specified"}</strong></span></div><p className="mt-2 text-[10px] leading-4 text-slate-500">Identity and contact details are shared after booking confirmation.</p><button disabled={busy === application.id} onClick={() => void act(application.id, () => acceptApplication(application.id))} className="primary-btn mt-2 w-full justify-center py-2 text-xs"><Check size={15} />{busy === application.id ? "Booking…" : "Book Now"}</button></div>; })}</div></section>}'''
new = '''{pendingPairings.length > 0 && <section className="mt-3"><h4 className="mb-2 flex items-center gap-2 text-base font-black text-[#017f27]"><span className="h-3 w-3 rounded-full bg-[#34A853]" />Applicants</h4><div className="space-y-2">{pendingPairings.map((application) => { const profile = application.professional_profiles; return <div key={application.id} className="rounded-xl border-2 border-[#34A853]/65 bg-[#f0fbf3] p-1 shadow-[0_8px_22px_rgba(52,168,83,0.10)]"><div className="rounded-lg bg-white p-3"><div className="mb-2 flex items-center justify-between gap-2 rounded-lg bg-[#eaf8ee] px-2.5 py-2"><span className="text-xs font-black text-[#017f27]">✓ I’m Interested</span><span className="font-mono text-xs font-black tabular-nums text-[#017f27]">{interestElapsed(application.created_at, nowMs)}</span></div><h5 className="font-black text-[#032757]">{profile?.profession || shift.profession}</h5><p className="mt-1 text-[11px] font-bold text-[#017f27]">{profile?.licence_province ? `Licence province: ${profile.licence_province}` : "Credential status unavailable"}</p><div className="mt-2 grid grid-cols-2 gap-x-2 gap-y-1 text-[11px] text-slate-600"><span>Rating: <strong>{profile?.rating ? `${profile.rating}★` : "No rating yet"}</strong></span><span>Completed: <strong>{profile?.completed_shifts || 0}</strong></span><span>Reliability: <strong>{profile?.reliability_score != null ? `${profile.reliability_score}%` : "Not enough history"}</strong></span><span>Requested rate: <strong>{application.proposed_rate != null ? `$${Number(application.proposed_rate).toFixed(2)}/hr` : "Not specified"}</strong></span></div><p className="mt-2 text-[10px] leading-4 text-slate-500">Identity and contact details are shared after booking confirmation.</p><button disabled={busy === application.id} onClick={() => void act(application.id, () => acceptApplication(application.id))} className="primary-btn mt-2 w-full justify-center py-2 text-xs"><Check size={15} />{busy === application.id ? "Booking…" : "Book Now"}</button></div></div>; })}</div></section>}'''
if old not in text:
    raise SystemExit('Applicants block not found')
path.write_text(text.replace(old, new, 1))
