from pathlib import Path

path = Path('components/WorkflowWorkspaceV2.tsx')
text = path.read_text()

old_day_requests = '''            const dayRequests = officeRequests.filter((application) => application.shifts && localDateKey(application.shifts.starts_at) === key);\n            const firstAvailability = dayAvailability[0];'''
new_day_requests = '''            const dayRequests = officeRequests.filter((application) => application.shifts && localDateKey(application.shifts.starts_at) === key);\n            const matchingOfficeRequests = professionShifts.filter((shift) => localDateKey(shift.starts_at) === key);\n            const firstAvailability = dayAvailability[0];'''
if old_day_requests not in text:
    raise SystemExit('calendar day request anchor not found')
text = text.replace(old_day_requests, new_day_requests, 1)

old_top = '''                <div className="flex max-w-[72%] flex-wrap justify-end gap-1 pointer-events-auto">\n                  {dayBookings.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "booking", id: dayBookings[0].id })} title={`${dayBookings.length} confirmed booking${dayBookings.length === 1 ? "" : "s"}`} className="rounded-full bg-[#eaf8ee] px-2 py-1 text-[10px] font-black text-[#017f27] shadow-sm">{dayBookings.length > 1 ? `${dayBookings.length} booked` : "Booked"}</button>}\n                  {dayRequests.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "request", id: dayRequests[0].id })} title={`${dayRequests.length} office request${dayRequests.length === 1 ? "" : "s"}`} className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-800 shadow-sm">{dayRequests.length > 1 ? `${dayRequests.length} requests` : "Request"}</button>}\n                </div>'''
new_top = '''                <div className="flex max-w-[78%] flex-wrap justify-end gap-1 pointer-events-auto">\n                  {matchingOfficeRequests.length > 0 && <button type="button" onClick={() => chooseDate(day)} title={`${matchingOfficeRequests.length} office request${matchingOfficeRequests.length === 1 ? "" : "s"} for ${signedRoleStyle.label}`} className="rounded-lg bg-[#F21C13] px-2 py-1 text-[10px] font-black text-white shadow-sm">Office Request · {matchingOfficeRequests.length}</button>}\n                  {dayBookings.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "booking", id: dayBookings[0].id })} title={`${dayBookings.length} confirmed booking${dayBookings.length === 1 ? "" : "s"}`} className="rounded-full bg-[#eaf8ee] px-2 py-1 text-[10px] font-black text-[#017f27] shadow-sm">{dayBookings.length > 1 ? `${dayBookings.length} booked` : "Booked"}</button>}\n                  {dayRequests.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "request", id: dayRequests[0].id })} title={`${dayRequests.length} direct office invitation${dayRequests.length === 1 ? "" : "s"}`} className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-800 shadow-sm">{dayRequests.length > 1 ? `${dayRequests.length} invites` : "Invite"}</button>}\n                </div>'''
if old_top not in text:
    raise SystemExit('calendar top-half block not found')
text = text.replace(old_top, new_top, 1)

anchor = '''            </section>\n\n            {(selectedDayBookings.length > 0 || selectedDayRequests.length > 0) && <section>'''
requests_section = '''            </section>\n\n            {selectedDayShifts.length > 0 && <section>\n              <div className="flex items-center justify-between gap-2"><h4 className="font-black text-[#002757]">Office Requests</h4><span className="rounded-full bg-[#F21C13] px-2.5 py-1 text-xs font-black text-white">{selectedDayShifts.length}</span></div>\n              <div className="mt-3 space-y-2">{selectedDayShifts.map((shift) => {\n                const application = workflow.applications.find((item) => item.shifts?.id === shift.id);\n                return <article key={shift.id} className="rounded-xl border border-[#F21C13]/25 bg-red-50/60 p-3">\n                  <div className="flex items-start justify-between gap-2"><div className="min-w-0"><strong className="block truncate text-sm text-[#002757]">{shift.offices?.name || "Dental office"}</strong><p className="mt-1 text-xs font-bold text-slate-600">{shortTime(shift.starts_at)}–{shortTime(shift.ends_at)} · ${Number(shift.hourly_rate)}/hr</p>{shift.offices && <p className="mt-1 text-[11px] text-slate-500">{shift.offices.city}, {shift.offices.province}</p>}</div>{preferredOfficeIds.includes(shift.office_id) && <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-[#FDB605] px-2 py-1 text-[10px] font-black text-white"><Star size={10} className="fill-white" />Preferred</span>}</div>\n                  <div className="mt-3">{application ? <span className="inline-flex rounded-full bg-white px-2.5 py-1 text-[11px] font-extrabold text-[#002757]">{application.status.replace("_", " ")}</span> : <button type="button" disabled={busy === `apply-${shift.id}`} onClick={() => void act(`apply-${shift.id}`, () => applyForShift({ shiftId: shift.id, professionalId: userId }))} className="primary-btn w-full justify-center">{busy === `apply-${shift.id}` ? "Applying…" : "Apply"}</button>}</div>\n                </article>;\n              })}</div>\n            </section>}\n\n            {(selectedDayBookings.length > 0 || selectedDayRequests.length > 0) && <section>'''
if anchor not in text:
    raise SystemExit('selected date insertion anchor not found')
text = text.replace(anchor, requests_section, 1)

path.write_text(text)
