from pathlib import Path

path = Path('components/WorkflowWorkspaceV2.tsx')
text = path.read_text()

old_state = '  const [cancelBookingTarget, setCancelBookingTarget] = useState<WorkflowBooking | null>(null);\n  const [nowMs, setNowMs] = useState(() => Date.now());'
new_state = '  const [cancelBookingTarget, setCancelBookingTarget] = useState<WorkflowBooking | null>(null);\n  const [viewShiftBookingId, setViewShiftBookingId] = useState<string | null>(null);\n  const [nowMs, setNowMs] = useState(() => Date.now());'
assert old_state in text, 'state anchor not found'
text = text.replace(old_state, new_state, 1)

old = '''action={<div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => onNavigate("bookings")} className="secondary-btn justify-center">View Shift</button><button type="button" disabled={busy === `cancel-booking-${booking.id}`} onClick={() => setCancelBookingTarget(booking)} className="secondary-btn justify-center border-rose-200 text-rose-700 hover:bg-rose-50">{busy === `cancel-booking-${booking.id}` ? "Cancelling…" : "Cancel Shift"}</button></div>}'''
new = '''action={<div className="space-y-3"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setViewShiftBookingId((current) => current === booking.id ? null : booking.id)} className="secondary-btn justify-center">{viewShiftBookingId === booking.id ? "Hide Shift" : "View Shift"}</button><button type="button" disabled={busy === `cancel-booking-${booking.id}`} onClick={() => setCancelBookingTarget(booking)} className="secondary-btn justify-center border-rose-200 text-rose-700 hover:bg-rose-50">{busy === `cancel-booking-${booking.id}` ? "Cancelling…" : "Cancel Shift"}</button></div>{viewShiftBookingId === booking.id && booking.shifts && <div className="rounded-xl border border-[#4285F4]/25 bg-blue-50/50 p-3 text-xs text-slate-700"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#4285F4]">Shift Details</p><div className="mt-2 grid gap-2 sm:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Date</p><p className="mt-0.5 font-extrabold text-[#002757]">{new Date(booking.shifts.starts_at).toLocaleDateString("en-CA", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Time</p><p className="mt-0.5 font-extrabold text-[#002757]">{shortTime(booking.shifts.starts_at)}–{shortTime(booking.shifts.ends_at)}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Position</p><p className="mt-0.5 font-extrabold text-[#002757]">{booking.shifts.profession}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Hourly Rate</p><p className="mt-0.5 font-extrabold text-[#002757]">${Number(booking.shifts.hourly_rate).toFixed(2)}/hr</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Required Software</p><p className="mt-0.5 font-extrabold text-[#002757]">{booking.shifts.required_software || "None specified"}</p></div><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Office</p><p className="mt-0.5 font-extrabold text-[#002757]">{booking.shifts.offices?.name || "Dental Office"}</p></div>{booking.shifts.notes && <div className="sm:col-span-2"><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">Shift Notes</p><p className="mt-0.5 font-semibold text-slate-700">{booking.shifts.notes}</p></div>}</div></div>}</div>}'''
assert old in text, 'scheduled action anchor not found'
text = text.replace(old, new, 1)
path.write_text(text)
print('patched')
