from pathlib import Path

path = Path('components/WorkflowWorkspaceV2.tsx')
text = path.read_text()

old = '''              <div className="relative z-10 flex items-start justify-between gap-1 pointer-events-none">\n                <span className={`inline-grid h-7 w-7 place-items-center rounded-full text-sm font-black ${today ? "bg-[#002757] text-white" : ""}`}>{day.getDate()}</span>\n                <div className="flex max-w-[78%] flex-wrap justify-end gap-1 pointer-events-auto">\n                  {matchingOfficeRequests.length > 0 && <button type="button" onClick={() => chooseDate(day)} title={`${matchingOfficeRequests.length} office request${matchingOfficeRequests.length === 1 ? "" : "s"} for ${signedRoleStyle.label}`} className="inline-flex max-w-full items-center gap-1 rounded-lg bg-[#F21C13] px-2 py-1.5 text-[9px] font-black leading-none text-white shadow-sm"><span className="whitespace-nowrap">Office Request</span><span className="inline-grid h-4 min-w-4 place-items-center rounded-full bg-white/20 px-1 text-[9px]">{matchingOfficeRequests.length}</span></button>}\n                  {dayBookings.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "booking", id: dayBookings[0].id })} title={`${dayBookings.length} confirmed booking${dayBookings.length === 1 ? "" : "s"}`} className="rounded-full bg-[#eaf8ee] px-2 py-1 text-[10px] font-black text-[#017f27] shadow-sm">{dayBookings.length > 1 ? `${dayBookings.length} booked` : "Booked"}</button>}\n                  {dayRequests.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "request", id: dayRequests[0].id })} title={`${dayRequests.length} direct office invitation${dayRequests.length === 1 ? "" : "s"}`} className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-800 shadow-sm">{dayRequests.length > 1 ? `${dayRequests.length} invites` : "Invite"}</button>}\n                </div>\n              </div>'''

new = '''              <div className="relative z-10 pointer-events-none">\n                <span className={`inline-grid h-7 w-7 place-items-center rounded-full text-sm font-black ${today ? "bg-[#002757] text-white" : ""}`}>{day.getDate()}</span>\n                <div className="pointer-events-auto mt-1.5 space-y-1">\n                  {matchingOfficeRequests.length > 0 && <button type="button" onClick={() => chooseDate(day)} title={`${matchingOfficeRequests.length} office request${matchingOfficeRequests.length === 1 ? "" : "s"} for ${signedRoleStyle.label}`} className="flex w-full items-center justify-between gap-2 rounded-lg bg-[#F21C13] px-2 py-1.5 text-[9px] font-black leading-none text-white shadow-sm"><span className="whitespace-nowrap">Office Request</span><span className="inline-grid h-4 min-w-4 shrink-0 place-items-center rounded-full bg-white/20 px-1 text-[9px]">{matchingOfficeRequests.length}</span></button>}\n                  <div className="flex flex-wrap gap-1">\n                    {dayBookings.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "booking", id: dayBookings[0].id })} title={`${dayBookings.length} confirmed booking${dayBookings.length === 1 ? "" : "s"}`} className="rounded-full bg-[#eaf8ee] px-2 py-1 text-[10px] font-black text-[#017f27] shadow-sm">{dayBookings.length > 1 ? `${dayBookings.length} booked` : "Booked"}</button>}\n                    {dayRequests.length > 0 && <button type="button" onClick={() => chooseItem(day, { type: "request", id: dayRequests[0].id })} title={`${dayRequests.length} direct office invitation${dayRequests.length === 1 ? "" : "s"}`} className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-black text-amber-800 shadow-sm">{dayRequests.length > 1 ? `${dayRequests.length} invites` : "Invite"}</button>}\n                  </div>\n                </div>\n              </div>'''

if old not in text:
    raise SystemExit('office request calendar header block not found')
text = text.replace(old, new, 1)
path.write_text(text)
