from pathlib import Path

path = Path("components/OfficeWorkspaceV2.tsx")
text = path.read_text()

old = '''            const dayAvailability = data.availability.filter((slot) => localDateKey(slot.starts_at) === key);\n            const availableByRole = (["RDH", "CDA", "DA", "ST"] as RoleCode[]).map((code) => ({ code, count: dayAvailability.filter((slot) => roleCode(slot.professional_profiles?.profession) === code).length })).filter((item) => item.count > 0);\n            return <button type="button" key={key} onClick={() => { setSelectedDate(key); setCalendarCursor(day); }} className={`relative min-h-24 bg-white p-1.5 pt-10 text-left transition hover:bg-blue-50 sm:min-h-28 sm:p-2 sm:pt-10 ${calendarView === "month" && !inMonth ? "text-slate-300" : "text-slate-800"} ${selected ? "z-10 bg-blue-50/50 ring-2 ring-inset ring-[#0078FE]" : ""}`}>\n              <span className={`absolute left-2 top-2 inline-grid h-7 w-7 place-items-center rounded-full text-sm font-black ${today ? "bg-[#032757] text-white" : ""}`}>{day.getDate()}</span>\n              <div className="space-y-1">{dayShifts.length > 0 && <div className="truncate rounded-lg bg-[#eaf8ee] px-1.5 py-1 text-[10px] font-black text-[#017f27]"><span className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-[#04A62F]" />Shift(s) Posted</div>}</div>\n            </button>;'''

new = '''            const dayAvailability = data.availability.filter((slot) => localDateKey(slot.starts_at) === key);\n            const availableByRole = (["RDH", "CDA", "DA", "ST"] as RoleCode[]).map((code) => ({ code, count: dayAvailability.filter((slot) => roleCode(slot.professional_profiles?.profession) === code).length })).filter((item) => item.count > 0);\n            const interestedCount = dayShifts.reduce((total, shift) => total + (shift.applications || []).filter((item) => item.status === "applied").length, 0);\n            return <button type="button" key={key} onClick={() => { setSelectedDate(key); setCalendarCursor(day); }} className={`relative min-h-24 bg-white p-1.5 text-left transition hover:bg-blue-50 sm:min-h-28 sm:p-2 ${calendarView === "month" && !inMonth ? "text-slate-300" : "text-slate-800"} ${selected ? "z-10 bg-blue-50/50 ring-2 ring-inset ring-[#0078FE]" : ""}`}>\n              <span className={`absolute left-2 top-2 inline-grid h-7 w-7 place-items-center rounded-full text-sm font-black ${today ? "bg-[#032757] text-white" : ""}`}>{day.getDate()}</span>\n              {dayShifts.length > 0 && <div className="absolute left-1.5 right-1.5 top-9 truncate rounded-lg bg-[#eaf8ee] px-1.5 py-1 text-[10px] font-black text-[#017f27] sm:left-2 sm:right-2"><span className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-[#04A62F]" />Shift(s) Posted</div>}\n              {interestedCount > 0 && <div className="absolute bottom-1.5 left-1.5 right-1.5 truncate rounded-lg bg-[#F21C13] px-1.5 py-1 text-[10px] font-black text-white sm:bottom-2 sm:left-2 sm:right-2">{interestedCount} interested · View day</div>}\n            </button>;'''

if old not in text:
    raise SystemExit("office calendar day status block not found")

path.write_text(text.replace(old, new, 1))
