name: Verify monthly billing

on:
  push:
    paths:
      - '.github/workflows/verify-monthly-billing.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Production build
        run: npm run build
